fixed_places_iconsdir = join_paths(fixed_iconsdir, 'places')

regular_files = [
    # DO NOT REMOVE: Begining of regular segment
    'folder-3dbenchy.svg',
    'folder-android.svg',
    'folder-appimage.svg',
    'folder-archlinux.svg',
    'folder-arduino.svg',
    'folder-backup.svg',
    'folder-bitwig.svg',
    'folder-blender.svg',
    'folder-books.svg',
    'folder-c.svg',
    'folder-camera.svg',
    'folder-cd.svg',
    'folder-cloud.svg',
    'folder-code.svg',
    'folder-codeberg.svg',
    'folder-computer.svg',
    'folder-container.svg',
    'folder-cplusplus.svg',
    'folder-csharp.svg',
    'folder-docker.svg',
    'folder-drawer.svg',
    'folder-dropbox.svg',
    'folder-earth.svg',
    'folder-emacs.svg',
    'folder-extensions.svg',
    'folder-fedora.svg',
    'folder-flatpak.svg',
    'folder-freecad.svg',
    'folder-games-card.svg',
    'folder-games.svg',
    'folder-gimp.svg',
    'folder-git-alt.svg',
    'folder-git.svg',
    'folder-github.svg',
    'folder-gitlab.svg',
    'folder-globe.svg',
    'folder-gnome.svg',
    'folder-go.svg',
    'folder-godot.svg',
    'folder-google-drive.svg',
    'folder-inkscape.svg',
    'folder-java.svg',
    'folder-kde.svg',
    'folder-kicad.svg',
    'folder-local.svg',
    'folder-lua.svg',
    'folder-mega.svg',
    'folder-money.svg',
    'folder-musescore.svg',
    'folder-neovim.svg',
    'folder-nextcloud.svg',
    'folder-nix.svg',
    'folder-obs.svg',
    'folder-obsidian.svg',
    'folder-onedrive.svg',
    'folder-openscad.svg',
    'folder-opensuse.svg',
    'folder-platformio.svg',
    'folder-plugdata.svg',
    'folder-podcast.svg',
    'folder-podman.svg',
    'folder-private.svg',
    'folder-projects.svg',
    'folder-python.svg',
    'folder-r.svg',
    'folder-raspberry-pi.svg',
    'folder-reaper.svg',
    'folder-recent.svg',
    'folder-redhat.svg',
    'folder-roms.svg',
    'folder-ruby.svg',
    'folder-rust.svg',
    'folder-school.svg',
    'folder-screencast.svg',
    'folder-screenshot.svg',
    'folder-script.svg',
    'folder-shell.svg',
    'folder-snap.svg',
    'folder-syncthing.svg',
    'folder-temp.svg',
    'folder-torrent.svg',
    'folder-translation.svg',
    'folder-ubuntu.svg',
    'folder-user.svg',
    'folder-vala.svg',
    'folder-windows-10.svg',
    'folder-windows.svg',
    'folder-wine.svg',
    'folder-work.svg',
    'go-home.svg',
    # DO NOT REMOVE: End of regular segment
]

link_files = {
    # DO NOT REMOVE: Begining of link segment
    'folder-work.svg': [
        'folder-work-legacy.svg',
    ],
    'folder-wine.svg': [
        'folder-wine-legacy.svg',
    ],
    'folder-windows.svg': [
        'folder-windows-legacy.svg',
    ],
    'folder-windows-10.svg': [
        'folder-windows-10-legacy.svg',
    ],
    'folder-vala.svg': [
        'folder-vala-legacy.svg',
    ],
    'folder-user.svg': [
        'folder-user-legacy.svg',
    ],
    'folder-ubuntu.svg': [
        'folder-ubuntu-legacy.svg',
    ],
    'folder-translation.svg': [
        'folder-translation-legacy.svg',
    ],
    'folder-torrent.svg': [
        'folder-torrent-legacy.svg',
    ],
    'folder-temp.svg': [
        'folder-temp-legacy.svg',
    ],
    'folder-syncthing.svg': [
        'folder-syncthing-legacy.svg',
    ],
    'folder-snap.svg': [
        'folder-snap-legacy.svg',
    ],
    'folder-shell.svg': [
        'folder-shell-legacy.svg',
    ],
    'folder-script.svg': [
        'folder-script-legacy.svg',
    ],
    'folder-screenshot.svg': [
        'folder-screenshot-legacy.svg',
    ],
    'folder-screencast.svg': [
        'folder-screencast-legacy.svg',
    ],
    'folder-school.svg': [
        'folder-school-legacy.svg',
    ],
    'folder-rust.svg': [
        'folder-rust-legacy.svg',
    ],
    'folder-ruby.svg': [
        'folder-ruby-legacy.svg',
    ],
    'folder-roms.svg': [
        'folder-roms-legacy.svg',
    ],
    'folder-redhat.svg': [
        'folder-redhat-legacy.svg',
    ],
    'folder-reaper.svg': [
        'folder-reaper-legacy.svg',
    ],
    'folder-raspberry-pi.svg': [
        'folder-raspberry-pi-legacy.svg',
    ],
    'folder-r.svg': [
        'folder-r-legacy.svg',
    ],
    'folder-python.svg': [
        'folder-python-legacy.svg',
    ],
    'folder-projects.svg': [
        'folder-projects-legacy.svg',
    ],
    'folder-private.svg': [
        'folder-private-legacy.svg',
    ],
    'folder-podman.svg': [
        'folder-podman-legacy.svg',
    ],
    'folder-podcast.svg': [
        'folder-podcast-legacy.svg',
    ],
    'folder-plugdata.svg': [
        'folder-plugdata-legacy.svg',
    ],
    'folder-platformio.svg': [
        'folder-platformio-legacy.svg',
    ],
    'folder-opensuse.svg': [
        'folder-opensuse-legacy.svg',
    ],
    'folder-openscad.svg': [
        'folder-openscad-legacy.svg',
    ],
    'folder-onedrive.svg': [
        'folder-onedrive-legacy.svg',
    ],
    'folder-obsidian.svg': [
        'folder-obsidian-legacy.svg',
    ],
    'folder-obs.svg': [
        'folder-obs-legacy.svg',
    ],
    'folder-nix.svg': [
        'folder-nix-legacy.svg',
    ],
    'folder-nextcloud.svg': [
        'folder-nextcloud-legacy.svg',
    ],
    'folder-neovim.svg': [
        'folder-neovim-legacy.svg',
    ],
    'folder-musescore.svg': [
        'folder-musescore-legacy.svg',
    ],
    'folder-money.svg': [
        'folder-money-legacy.svg',
    ],
    'folder-mega.svg': [
        'folder-mega-legacy.svg',
    ],
    'folder-lua.svg': [
        'folder-lua-legacy.svg',
    ],
    'folder-local.svg': [
        'folder-local-legacy.svg',
    ],
    'folder-kicad.svg': [
        'folder-kicad-legacy.svg',
    ],
    'folder-kde.svg': [
        'folder-kde-legacy.svg',
    ],
    'folder-java.svg': [
        'folder-java-legacy.svg',
    ],
    'folder-inkscape.svg': [
        'folder-inkscape-legacy.svg',
    ],
    'folder-google-drive.svg': [
        'folder-google-drive-legacy.svg',
    ],
    'folder-godot.svg': [
        'folder-godot-legacy.svg',
    ],
    'folder-go.svg': [
        'folder-go-legacy.svg',
    ],
    'folder-gnome.svg': [
        'folder-gnome-legacy.svg',
    ],
    'folder-globe.svg': [
        'folder-globe-legacy.svg',
    ],
    'folder-gitlab.svg': [
        'folder-gitlab-legacy.svg',
    ],
    'folder-github.svg': [
        'folder-github-legacy.svg',
    ],
    'folder-git.svg': [
        'folder-git-legacy.svg',
    ],
    'folder-git-alt.svg': [
        'folder-git-alt-legacy.svg',
    ],
    'folder-gimp.svg': [
        'folder-gimp-legacy.svg',
    ],
    'folder-games.svg': [
        'folder-games-legacy.svg',
    ],
    'folder-games-card.svg': [
        'folder-games-card-legacy.svg',
    ],
    'folder-freecad.svg': [
        'folder-freecad-legacy.svg',
    ],
    'folder-flatpak.svg': [
        'folder-flatpak-legacy.svg',
    ],
    'folder-fedora.svg': [
        'folder-fedora-legacy.svg',
    ],
    'folder-extensions.svg': [
        'folder-extensions-legacy.svg',
    ],
    'folder-emacs.svg': [
        'folder-emacs-legacy.svg',
    ],
    'folder-earth.svg': [
        'folder-earth-legacy.svg',
    ],
    'folder-dropbox.svg': [
        'folder-dropbox-legacy.svg',
    ],
    'folder-drawer.svg': [
        'folder-drawer-legacy.svg',
    ],
    'folder-docker.svg': [
        'folder-docker-legacy.svg',
    ],
    'folder-csharp.svg': [
        'folder-csharp-legacy.svg',
    ],
    'folder-cplusplus.svg': [
        'folder-cplusplus-legacy.svg',
    ],
    'folder-container.svg': [
        'folder-container-legacy.svg',
    ],
    'folder-computer.svg': [
        'folder-computer-legacy.svg',
    ],
    'folder-codeberg.svg': [
        'folder-codeberg-legacy.svg',
    ],
    'folder-code.svg': [
        'folder-code-legacy.svg',
    ],
    'folder-cloud.svg': [
        'folder-cloud-legacy.svg',
    ],
    'folder-cd.svg': [
        'folder-cd-legacy.svg',
    ],
    'folder-camera.svg': [
        'folder-camera-legacy.svg',
    ],
    'folder-c.svg': [
        'folder-c-legacy.svg',
    ],
    'folder-books.svg': [
        'folder-books-legacy.svg',
    ],
    'folder-blender.svg': [
        'folder-blender-legacy.svg',
    ],
    'folder-backup.svg': [
        'folder-backup-legacy.svg',
    ],
    'folder-arduino.svg': [
        'folder-arduino-legacy.svg',
    ],
    'folder-archlinux.svg': [
        'folder-archlinux-legacy.svg',
    ],
    'folder-appimage.svg': [
        'folder-appimage-legacy.svg',
    ],
    'folder-android.svg': [
        'folder-android-legacy.svg',
    ],
    'folder-3dbenchy.svg': [
        'folder-3dbenchy-legacy.svg',
    ],
    'folder-recent.svg': [
        'document-open-recent.svg',
        'folder-recent-legacy.svg',
    ],
    'folder-bitwig.svg': [
        'com.bitwig.BitwigStudio.application-bitwig-project-folder-legacy.svg',
        'com.bitwig.BitwigStudio.application-bitwig-project-folder.svg',
        'folder-bitwig-legacy.svg',
    ],
    # DO NOT REMOVE: End of link segment
}

install_data(regular_files, install_dir: fixed_places_iconsdir)

foreach dest_file, link_files_for_dest : link_files
    foreach link_file : link_files_for_dest
        install_symlink(link_file, install_dir: fixed_places_iconsdir, pointing_to: dest_file)
    endforeach
endforeach
